SELECT
      A.LMT_CL_CD
    , C.CD_VAL_NM AS LMT_CL_CD_CM
    , A.STD_AMT
    , A.AVL_STA_DT
    , A.AVL_END_DT
    , A.LS_ORT_EMP_NO
    , TO_CHAR(A.LS_ORT_DTL_DTM, 'YYYYMMDD') AS LS_ORT_DTL_DTM
FROM TB_LMT_STD_MGMT A
    INNER JOIN (
         SELECT LMT_CL_CD, MAX(LS_ORT_DTL_DTM) AS MAX_LS_ORT_DTL_DTM
           FROM TB_LMT_STD_MGMT
          WHERE LMT_CL_CD IN ('1010', '1020', '1030')
          GROUP BY LMT_CL_CD
         ) B
    ON A.LMT_CL_CD = B.LMT_CL_CD
        AND A.LS_ORT_DTL_DTM = B.MAX_LS_ORT_DTL_DTM
    LEFT JOIN TB_CM_CD C
        ON C.CM_CD = 'LMT_CL_CD' AND C.CD_VAL = A.LMT_CL_CD
ORDER BY A.LMT_CL_CD
